example_browser: BrowserModel Class Reference
BrowserModel Class Reference
Public Member Functions
BrowserModel ()
URL next ()
URL back ()
URL go (String url)
boolean hasNext ()
boolean hasPrevious ()
URL getHome ()
void setHome ()
void addFavorite (String name)
URL getFavorite (String name)
Static Public Attributes
static final String PROTOCOL_PREFIX = "http://"
Private Member Functions
URL completeURL (String possible) throws MalformedURLException
Private Attributes
URL myHome
URL myCurrentURL
int myCurrentIndex
List< URL > myHistory
Map< String, URL > myFavorites
Detailed Description
This represents the heart of the browser: the collections that organize all the URLs into useful structures.
Author
Robert C. Duvall
Definition at line 15 of file BrowserModel.java.
Constructor & Destructor Documentation
BrowserModel.BrowserModel ()
Creates an empty model.
Definition at line 29 of file BrowserModel.java.
Member Function Documentation
void BrowserModel.addFavorite (String name)
Adds current URL being viewed to favorites collection with given name.
Definition at line 115 of file BrowserModel.java.
Referenced by BrowserView.addFavorite().
URL BrowserModel.back ()
Returns the first page in back history, null if back history is empty.
Definition at line 53 of file BrowserModel.java.
References hasPrevious().
Referenced by BrowserView.back().
URL BrowserModel.completeURL (String possible) throws MalformedURLException private
Definition at line 135 of file BrowserModel.java.
Referenced by go().
URL BrowserModel.getFavorite (String name)
Returns URL from favorites associated with given name, null if none set.
Definition at line 125 of file BrowserModel.java.
Referenced by BrowserView.showFavorite().
URL BrowserModel.getHome ()
Returns URL of the current home page or null if none is set.
Definition at line 98 of file BrowserModel.java.
References myHome.
Referenced by BrowserView.enableButtons(), and BrowserView.home().
URL BrowserModel.go (String url)
Changes current page to given URL, removing next history.
Definition at line 66 of file BrowserModel.java.
References completeURL(), hasNext(), and myCurrentURL.
Referenced by BrowserView.showPage().
boolean BrowserModel.hasNext ()
Returns true if there is a next URL available
Definition at line 84 of file BrowserModel.java.
Referenced by BrowserView.enableButtons(), go(), and next().
boolean BrowserModel.hasPrevious ()
Returns true if there is a previous URL available
Definition at line 91 of file BrowserModel.java.
Referenced by back(), and BrowserView.enableButtons().
URL BrowserModel.next ()
Returns the first page in next history, null if next history is empty.
Definition at line 40 of file BrowserModel.java.
References hasNext().
Referenced by BrowserView.next().
void BrowserModel.setHome ()
Sets current home page to the current URL being viewed.
Definition at line 105 of file BrowserModel.java.
References myCurrentURL.
Referenced by BrowserView.makePreferencesPanel().
Member Data Documentation
int BrowserModel.myCurrentIndex private
Definition at line 21 of file BrowserModel.java.
URL BrowserModel.myCurrentURL private
Definition at line 20 of file BrowserModel.java.
Referenced by go(), and setHome().
Map<String, URL> BrowserModel.myFavorites private
Definition at line 23 of file BrowserModel.java.
List<URL> BrowserModel.myHistory private
Definition at line 22 of file BrowserModel.java.
URL BrowserModel.myHome private
Definition at line 19 of file BrowserModel.java.
Referenced by getHome().
final String BrowserModel.PROTOCOL_PREFIX = "http://" static
Definition at line 17 of file BrowserModel.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_browser/repository/src/BrowserModel.java