example_browser: BrowserView Class Reference
BrowserView Class Reference
Classes
class LinkListener
class ShowPage
Public Member Functions
BrowserView (BrowserModel model, String language)
void showPage (String url)
Scene getScene ()
void showStatus (String message)
void showError (String message)
Static Public Attributes
static final Dimension DEFAULT_SIZE = new Dimension(800, 600)
static final String DEFAULT_RESOURCE_PACKAGE = "resources/"
static final String IMAGEFILE_SUFFIXES
static final String BLANK = " "
Private Member Functions
void next ()
void back ()
void home ()
void showFavorite (String favorite)
void update (URL url)
void addFavorite ()
void enableButtons ()
Node makePageDisplay ()
Node makeInputPanel ()
Node makeInformationPanel ()
Node makeNavigationPanel ()
Node makePreferencesPanel ()
Button makeButton (String property, EventHandler< ActionEvent > handler)
TextField makeInputField (int width, EventHandler< ActionEvent > handler)
Private Attributes
Scene myScene
WebView myPage
Label myStatus
TextField myURLDisplay
Button myBackButton
Button myNextButton
Button myHomeButton
ComboBox< String > myFavorites
ResourceBundle myResources
BrowserModel myModel
Detailed Description
A class used to display the viewer for a simple HTML browser.
See this tutorial for help on how to use the variety of components: http://download.oracle.com/otndocs/products/javafx/2/samples/Ensemble/
Author
Owen Astrachan
Marcin Dobosz
Yuzhang Han
Edwin Ward
Robert C. Duvall
Definition at line 44 of file BrowserView.java.
Constructor & Destructor Documentation
BrowserView.BrowserView (BrowserModel model, String language)
Create a view of the given model of a web browser.
Definition at line 73 of file BrowserView.java.
References enableButtons(), makeInformationPanel(), makeInputPanel(), and makePageDisplay().
Member Function Documentation
void BrowserView.addFavorite () private
Definition at line 149 of file BrowserView.java.
References BrowserModel.addFavorite().
Referenced by makePreferencesPanel().
void BrowserView.back () private
Definition at line 127 of file BrowserView.java.
References BrowserModel.back(), and update().
Referenced by makeNavigationPanel().
void BrowserView.enableButtons () private
Definition at line 162 of file BrowserView.java.
References BrowserModel.getHome(), BrowserModel.hasNext(), and BrowserModel.hasPrevious().
Referenced by BrowserView(), makePreferencesPanel(), and update().
Scene BrowserView.getScene ()
Returns scene for this view so it can be added to stage.
Definition at line 103 of file BrowserView.java.
References myScene.
Referenced by Main.start().
void BrowserView.home () private
Definition at line 132 of file BrowserView.java.
References BrowserModel.getHome(), and showPage().
Referenced by makeNavigationPanel().
Button BrowserView.makeButton (String property, EventHandler< ActionEvent > handler) private
Definition at line 229 of file BrowserView.java.
Referenced by makeNavigationPanel(), and makePreferencesPanel().
Node BrowserView.makeInformationPanel () private
Definition at line 184 of file BrowserView.java.
References myStatus.
Referenced by BrowserView().
TextField BrowserView.makeInputField (int width, EventHandler< ActionEvent > handler) private
Definition at line 243 of file BrowserView.java.
Referenced by makeNavigationPanel().
Node BrowserView.makeInputPanel () private
Definition at line 177 of file BrowserView.java.
References makeNavigationPanel(), and makePreferencesPanel().
Referenced by BrowserView().
Node BrowserView.makeNavigationPanel () private
Definition at line 191 of file BrowserView.java.
References back(), home(), makeButton(), makeInputField(), and next().
Referenced by makeInputPanel().
Node BrowserView.makePageDisplay () private
Definition at line 169 of file BrowserView.java.
References myPage.
Referenced by BrowserView().
Node BrowserView.makePreferencesPanel () private
Definition at line 214 of file BrowserView.java.
References addFavorite(), enableButtons(), makeButton(), BrowserModel.setHome(), and showFavorite().
Referenced by makeInputPanel().
void BrowserView.next () private
Definition at line 122 of file BrowserView.java.
References BrowserModel.next(), and update().
Referenced by makeNavigationPanel().
void BrowserView.showError (String message)
Display given message as an error in the GUI.
Definition at line 117 of file BrowserView.java.
Referenced by showPage().
void BrowserView.showFavorite (String favorite) private
Definition at line 137 of file BrowserView.java.
References BrowserModel.getFavorite(), and showPage().
Referenced by makePreferencesPanel().
void BrowserView.showPage (String url)
Display given URL.
Definition at line 91 of file BrowserView.java.
References BrowserModel.go(), showError(), and update().
Referenced by BrowserView.LinkListener.changed(), BrowserView.ShowPage.handle(), home(), showFavorite(), and Main.start().
void BrowserView.showStatus (String message)
Display given message as information in the GUI.
Definition at line 110 of file BrowserView.java.
Referenced by BrowserView.LinkListener.changed().
void BrowserView.update (URL url) private
Definition at line 142 of file BrowserView.java.
References enableButtons().
Referenced by back(), next(), and showPage().
Member Data Documentation
final String BrowserView.BLANK = " " static
Definition at line 50 of file BrowserView.java.
final String BrowserView.DEFAULT_RESOURCE_PACKAGE = "resources/" static
Definition at line 47 of file BrowserView.java.
final Dimension BrowserView.DEFAULT_SIZE = new Dimension(800, 600) static
Definition at line 46 of file BrowserView.java.
final String BrowserView.IMAGEFILE_SUFFIXES static
Initial value:
=
        String.format(".*\\.(%s)", String.join("|", ImageIO.getReaderFileSuffixes()))
Definition at line 48 of file BrowserView.java.
Button BrowserView.myBackButton private
Definition at line 60 of file BrowserView.java.
ComboBox<String> BrowserView.myFavorites private
Definition at line 64 of file BrowserView.java.
Button BrowserView.myHomeButton private
Definition at line 62 of file BrowserView.java.
BrowserModel BrowserView.myModel private
Definition at line 68 of file BrowserView.java.
Button BrowserView.myNextButton private
Definition at line 61 of file BrowserView.java.
WebView BrowserView.myPage private
Definition at line 55 of file BrowserView.java.
Referenced by makePageDisplay().
ResourceBundle BrowserView.myResources private
Definition at line 66 of file BrowserView.java.
Scene BrowserView.myScene private
Definition at line 53 of file BrowserView.java.
Referenced by getScene().
Label BrowserView.myStatus private
Definition at line 57 of file BrowserView.java.
Referenced by makeInformationPanel().
TextField BrowserView.myURLDisplay private
Definition at line 59 of file BrowserView.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-spring2015/example_browser/repository/src/BrowserView.java